version: '3.7'

networks:
  yatrirakshak:
    name: yatrirakshak-network

volumes:
  orderer.yatrirakshak.com:
  peer0.tourism-dept.yatrirakshak.com:
  peer0.police-dept.yatrirakshak.com:
  peer0.entry-points.yatrirakshak.com:

services:
  # Orderer Service
  orderer.yatrirakshak.com:
    image: hyperledger/fabric-orderer:2.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.yatrirakshak.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./organizations/ordererOrganizations/yatrirakshak.com/orderers/orderer.yatrirakshak.com/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/yatrirakshak.com/orderers/orderer.yatrirakshak.com/tls:/var/hyperledger/orderer/tls
      - orderer.yatrirakshak.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - yatrirakshak

  # Tourism Department Peer
  peer0.tourism-dept.yatrirakshak.com:
    image: hyperledger/fabric-peer:2.4
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.tourism-dept.yatrirakshak.com
      - CORE_PEER_ADDRESS=peer0.tourism-dept.yatrirakshak.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.tourism-dept.yatrirakshak.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tourism-dept.yatrirakshak.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tourism-dept.yatrirakshak.com:7051
      - CORE_PEER_LOCALMSPID=TourismDeptMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.tourism-dept.yatrirakshak.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0tourism"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./organizations/peerOrganizations/tourism-dept.yatrirakshak.com/peers/peer0.tourism-dept.yatrirakshak.com:/etc/hyperledger/fabric
      - peer0.tourism-dept.yatrirakshak.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - yatrirakshak

  # Police Department Peer
  peer0.police-dept.yatrirakshak.com:
    image: hyperledger/fabric-peer:2.4
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.police-dept.yatrirakshak.com
      - CORE_PEER_ADDRESS=peer0.police-dept.yatrirakshak.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.police-dept.yatrirakshak.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.police-dept.yatrirakshak.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.police-dept.yatrirakshak.com:9051
      - CORE_PEER_LOCALMSPID=PoliceDeptMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.police-dept.yatrirakshak.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0police"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./organizations/peerOrganizations/police-dept.yatrirakshak.com/peers/peer0.police-dept.yatrirakshak.com:/etc/hyperledger/fabric
      - peer0.police-dept.yatrirakshak.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - yatrirakshak

  # Entry Points Peer
  peer0.entry-points.yatrirakshak.com:
    image: hyperledger/fabric-peer:2.4
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.entry-points.yatrirakshak.com
      - CORE_PEER_ADDRESS=peer0.entry-points.yatrirakshak.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.entry-points.yatrirakshak.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.entry-points.yatrirakshak.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.entry-points.yatrirakshak.com:11051
      - CORE_PEER_LOCALMSPID=EntryPointsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.entry-points.yatrirakshak.com:9446
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0entry"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ./organizations/peerOrganizations/entry-points.yatrirakshak.com/peers/peer0.entry-points.yatrirakshak.com:/etc/hyperledger/fabric
      - peer0.entry-points.yatrirakshak.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
      - 9446:9446
    networks:
      - yatrirakshak

  # Certificate Authorities
  ca.tourism-dept.yatrirakshak.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-tourism-dept
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/tourism-dept:/etc/hyperledger/fabric-ca-server
    container_name: ca.tourism-dept.yatrirakshak.com
    networks:
      - yatrirakshak

  ca.police-dept.yatrirakshak.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-police-dept
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "8054:8054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/police-dept:/etc/hyperledger/fabric-ca-server
    container_name: ca.police-dept.yatrirakshak.com
    networks:
      - yatrirakshak

  ca.entry-points.yatrirakshak.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-entry-points
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
    ports:
      - "9054:9054"
      - "19054:19054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/entry-points:/etc/hyperledger/fabric-ca-server
    container_name: ca.entry-points.yatrirakshak.com
    networks:
      - yatrirakshak

  # CLI for network administration
  cli:
    image: hyperledger/fabric-tools:2.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.tourism-dept.yatrirakshak.com:7051
      - CORE_PEER_LOCALMSPID=TourismDeptMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/tourism-dept.yatrirakshak.com/peers/peer0.tourism-dept.yatrirakshak.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/tourism-dept.yatrirakshak.com/peers/peer0.tourism-dept.yatrirakshak.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/tourism-dept.yatrirakshak.com/peers/peer0.tourism-dept.yatrirakshak.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/tourism-dept.yatrirakshak.com/users/Admin@tourism-dept.yatrirakshak.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./chaincodes:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincodes
    depends_on:
      - peer0.tourism-dept.yatrirakshak.com
      - peer0.police-dept.yatrirakshak.com
      - peer0.entry-points.yatrirakshak.com
    networks:
      - yatrirakshak